apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: techtrends
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort | default (.Values.service.port)}}
    {{- if eq .Values.service.targetPort nil}}
    targetPort: {{ .Values.service.port }}    
    {{- end }}
    protocol: TCP
  type: {{ .Values.service.type }}